export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT'; 
export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';
export const FETCH_SCHEDULES = 'FETCH_SCHEDULES';
export const FETCH_SCHEDULE = 'FETCH_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const EDIT_SCHEDULE = 'EDIT_SCHEDULE';